name: Docker Image CI

on:
  push:
    branches: [main]

env:
  OPENSSL_VERSION: 3.0.5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos_version: ["8", "9"]
        python_version: ["3.9.14", "3.10.7", "3.11.0rc2"]
    env:
      CENTOS_VERSION: ${{ matrix.centos_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Image
        run: |
          docker push ${DOCKERHUB_USERNAME}/centos-stream${CENTOS_VERSION}-python:${PYTHON_VERSION}
      - name: Retag to major.minor only (e.g. centos-stream9-python:3.10)
        run: |
          docker tag ${DOCKERHUB_USERNAME}/centos-stream${CENTOS_VERSION}-python:${PYTHON_VERSION} ${DOCKERHUB_USERNAME}/centos-stream${CENTOS_VERSION}-python:${PYTHON_VERSION%.*}
          docker push ${DOCKERHUB_USERNAME}/centos-stream${CENTOS_VERSION}-python:${PYTHON_VERSION%.*}
